### ISSUE TITLE
Extra Options

### ISSUE THREAD

**Issue by BigMan-JJ** [ImCodist/Friday-Night-Funkin-Gamemaker-Remake#13]
Here's some options I'd like, they might not be _too_ hard to implement:
Downscroll - Improves Readability of notes and makes them go, well, downwards
Note Speed - Makes notes go faster although are still in sync with the song

**Comment by ImCodist** [comment]
I will add this in the next update. 👍

**Comment by ImCodist** [comment]
I have added Downscroll, which will be released next update.
I decided against adding a Note Speed option, as there are already Note Speed modifiers.
