### ISSUE TITLE
Another Bug

### ISSUE THREAD

**Issue by Buttercarsen** [ImCodist/Friday-Night-Funkin-Gamemaker-Remake#8]
I finally realized that I should report this bug.
The last played battle dictate what icons show up in the top right of Freeplay mode, rather than hovering over a song.

![](https://user-images.githubusercontent.com/80850329/112329019-3147d280-8c8d-11eb-9a9f-4090dc5a640b.png)

**Comment by ImCodist** [comment]
Fixed via hotfix.
