### ISSUE TITLE
Very annoying conflictment

### ISSUE THREAD

**Issue by Buttercarsen** [ImCodist/Friday-Night-Funkin-Gamemaker-Remake#9]
Since the L key now does two different things (load a song in the debug menu and also do whatever that new song saver is), it is impossible as far as I can tell to actually load a song in the debug menu since it immediately fades out to the other thing. It's quite frustrating, if I do say so myself.

**Comment by ImCodist** [comment]
Working on it.

**Comment by ImCodist** [comment]
Fixed in a hotfix.
